### ISSUE TITLE
feature request: Obtain OEM info

### ISSUE THREAD

**Issue by seahurt** [yumaojun03/dmidecode#10]
like
```
sudo dmidecode -t 11
```

output like:
```
# dmidecode 3.2
Getting SMBIOS data from sysfs.
SMBIOS 3.2.0 present.

Handle 0x0B00, DMI type 11, 5 bytes
OEM Strings
	String 1: Dell System
	String 2: 5[0000]
	String 3: 14[1]
	String 4: 26[0]
	String 5: 17[A4B60183CF8FDCD8]
	String 6: 17[A6BDC5E1EE433F13]
	String 7: 18[0]
	String 8: 19[1]
	String 9: 19[1]
```

**Comment by yumaojun03** [comment]
[root@master1 ~]# ./dmidecode -t system
SMBIOS 2.7.0 - table: address: 0xe0010, size: 10240
Handle 1, DMI type 1, 27 bytes
	System Information
	Manufacturer: VMware, Inc.
	Product Name: VMware Virtual Platform
	Version: None
	Serial Number: xxxx
	UUID: xxxx
	Wake-up Type: Power Switch
	SKU Number: Unknown
	Family: Unknown
Handle 2c, DMI type 11, 5 bytes
OEM Strings
	String 1: [MS_VM_CERT/SHA1/27d66596a61c48dd3dc7216fd715126e33f59ae7]
	String 2: Welcome to the Virtual Machine

**Comment by seahurt** [comment]
dmidecode -t system cannot output type 11 info

The dmidecode man page has info like:

```

       Type   Information
       ────────────────────────────────────────────
          0   BIOS
          1   System
          2   Baseboard
          3   Chassis
          4   Processor
          5   Memory Controller
          6   Memory Module
          7   Cache
          8   Port Connector
          9   System Slots
         10   On Board Devices
         11   OEM Strings
         12   System Configuration Options
         ......
       Keyword     Types
       ──────────────────────────────
       bios        0, 13
       system      1, 12, 15, 23, 32
       baseboard   2, 10, 41

       chassis     3
       processor   4
       memory      5, 6, 16, 17
       cache       7
       connector   8
       slot        9
```

Seems type 11 OEM string won't be printed, or at lease not fully printed

**Comment by yumaojun03** [comment]
你cli  执行时，添加一个-d flag 把输出结果贴出来，我好确认原因发自我的华为手机-------- 原始邮件 --------发件人： seahurt ***@***.***>日期： 2021年4月7日周三 傍晚5:24收件人： yumaojun03/dmidecode ***@***.***>抄送： 紫川秀 ***@***.***>, State change ***@***.***>主    题： Re: [yumaojun03/dmidecode] feature request: Obtain OEM info (#10)

dmidecode -t system cannot output type 11 info

The dmidecode man page has info like:



       Type   Information

       ────────────────────────────────────────────

          0   BIOS

          1   System

          2   Baseboard

          3   Chassis

          4   Processor

          5   Memory Controller

          6   Memory Module

          7   Cache

          8   Port Connector

          9   System Slots

         10   On Board Devices

         11   OEM Strings

         12   System Configuration Options

         ......

       Keyword     Types

       ──────────────────────────────

       bios        0, 13

       system      1, 12, 15, 23, 32

       baseboard   2, 10, 41



       chassis     3

       processor   4

       memory      5, 6, 16, 17

       cache       7

       connector   8

       slot        9



Seems type 11 OEM string won't be printed, or at lease not fully printed

**Comment by yumaojun03** [comment]
[root@master1 ~]# ./dmidecode -t 11
SMBIOS 2.7.0 - table: address: 0xe0010, size: 10240
Handle 2c, DMI type 11, 5 bytes
OEM Strings
        String 1: [MS_VM_CERT/SHA1/27d66596a61c48dd3dc7216fd715126e33f59ae7]
        String 2: Welcome to the Virtual Machine
