### ISSUE TITLE
获取OEM信息时候报错

### ISSUE THREAD

**Issue by QinGTi** [yumaojun03/dmidecode#12]
dmi.OEM undefined (type *dmidecode.Decoder has no field or method OEM)
大佬帮看看。

**Comment by QinGTi** [comment]
啊，目前不支持，没事了。。。

**Comment by yumaojun03** [comment]
功能上支持，你可以查看这个问题: https://github.com/yumaojun03/dmidecode/issues/10

**Comment by QinGTi** [comment]
QAQ，大佬能通过这个工具获取MAC地址嘛，昨晚没搞出来，临时换了个招，用官方的net包解决的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yumaojun03/dmidecode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月23日(星期五) 中午1:45
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [yumaojun03/dmidecode] 获取OEM信息时候报错 (#12)





 
功能上支持，你可以查看这个问题: #10
