### ISSUE TITLE
机载设备获取不正确，On Board Device获取不出来

### ISSUE THREAD

**Issue by xx132917** [yumaojun03/dmidecode#2]
我的命令行输出：
      On Board Device 1 Information
        Type: Video
        Status: Disabled
        Description: VMware SVGA II
   On Board Device 2 Information
        Type: Sound
        Status: Disabled
        Description: ES1371
使用dmi.Onboard()获取失败：
     获取出来是这个：SMBIOS 2.7.0 - table: address: 0xe0010, size: 28932

**Comment by xx132917** [comment]
你写这个是编号41的，编号10的能支持一下吗？

**Comment by yumaojun03** [comment]
我没有测试数据，等我更新一版，提供 debug 打印二进制数据后，你再给我测试数据，完善功能，多谢你的意见发自我的华为手机-------- 原始邮件 --------发件人： xx132917 <notifications@github.com>日期： 2020年6月11日周四 傍晚6:58收件人： yumaojun03/dmidecode <dmidecode@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： Re: [yumaojun03/dmidecode] 机载设备获取不正确，On Board Device获取不出来 (#2)

你写这个是编号41的，编号10的能支持一下吗？

**Comment by xx132917** [comment]
我已经看到了你的提交了，我测试一下，这个是我dmidecde命令执行的输出https://github.com/xx132917/dmidecode/blob/master/test/dmi.txt

**Comment by yumaojun03** [comment]
从结果来看 解析出来2个设备
```
Handle 0x019F, DMI type 10, 8 bytes
On Board Device 1 Information
	Type: Video
	Status: Disabled
	Description: VMware SVGA II
On Board Device 2 Information
	Type: Sound
	Status: Disabled
	Description: ES1371
```

解析是按照 spec文档写的，测试用例也是按照 spec文档构建的,  结果应该没问题，你确认下，由于我本地没有测试环境(smbios < 2.6) ，如果有问题及时反馈。

**Comment by yumaojun03** [comment]
编译后 命令行 添加-d 参数 可以打印 smbios二进制数据, 如果解析出问题, 请将报错和二进制样例数据贴出来
```sh
[root@xxx]# ./dmidecode -d -t onboard
SMBIOS 2.7.0 - table: address: 0xe0010, size: 10240
[Debug] *smbios.Structure: Header: Type: 10, Length: 8, Handle: 43, Data: [3 1 7 2] Strings: [VMware SVGA II ES1371]
On Board Device 1 Information
        Device Type: Video
        Device Status: Disabled
        Description: VMware SVGA II
On Board Device 2 Information
        Device Type: Sound
        Device Status: Disabled
        Description: ES1371
```
