### ISSUE TITLE
cpuid似乎解析的不对

### ISSUE THREAD

**Issue by xx132917** [yumaojun03/dmidecode#3]
命令：dmidecode -t 4
# dmidecode 3.2
Getting SMBIOS data from sysfs.
SMBIOS 2.7 present.

Handle 0x0004, DMI type 4, 42 bytes
Processor Information
        Socket Designation: CPU #000
        Type: Central Processor
        Family: Unknown
        Manufacturer: GenuineIntel
        ID: EA 06 09 00 FF FB 8B 1F
        Version: Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
        Voltage: 3.3 V
        External Clock: Unknown
        Max Speed: 30000 MHz
        Current Speed: 3000 MHz
        Status: Populated, Enabled
        Upgrade: ZIF Socket
        L1 Cache Handle: 0x0094
        L2 Cache Handle: 0x0114
        L3 Cache Handle: Not Provided
        Serial Number: Not Specified
        Asset Tag: Not Specified
        Part Number: Not Specified
        Core Count: 2
        Core Enabled: 2
        Characteristics:
                64-bit capable
                Multi-Core
                Execute Protection
这是我命令行返回的CPU信息，我获取到的ID是0，我想获取的是这个 ID: EA 06 09 00 FF FB 8B 1F

**Comment by yumaojun03** [comment]
我需要debug数据, 获取方法
```
go run cmd/main.go -d -t processor
```
请把结果贴出来,  我基于你的数据编写测试用例, 方便修复。
