### ISSUE TITLE
友善R1S开发板不行

### ISSUE THREAD

**Issue by Leadrive** [yumaojun03/dmidecode#7]
ARM64，UBUNTU
failed to open stream: read /dev/mem: bad address

应该是dmi, err := dmidecode.New()就报错了

ls -l /dev/mem
crw-r----- 1 root kmem 1, 1 Feb 12  2016 /dev/mem

dmidecode 报
# dmidecode 3.0
# No SMBIOS nor DMI entry point found, sorry.

**Comment by yumaojun03** [comment]
我手上没有相应的环境，复现不了该情况

**Comment by yqchilde** [comment]
nvidia nx板子，arm架构 ubuntu系统，出现同样错误
